<?php
//\Yii::$app->params['copyright']
return [
    'copyright' => 'WebSea',
    'alias' => 'UTIMPOR S.A.',
    'siteName' => 'Tienda UTIMPOR S.A.',
    'web' => 'https://www.utimpor.com/',
    'telefonos' => '(593) 3-810300',
    'direccion' => 'Cdla. La Garzota Av. Hermano Miguel Solar 3 y Av. Agustin Freire',
    'version' => '1.0',
    'adminEmail' => 'admin@utimpor.com',
    'ventasEmail' => 'ventas@utimpor.com',
    'contactoEmail' => 'contacto@utimpor.com',
    'no-responder' => 'no-responder@utimpor.com',
    'soporte' => 'bvillacreses@utimpor.com',    
    'culture' => 'es-ES',
    'cookieSession' => 3600*24*30,
    'logfile' => __DIR__ . '/../runtime/logs/webapp.log',
    'limitRow' => 10,
    'pageSize' => 20,
    'pagePro' => 9,
    'dateTimeByDefault' => 'Y-m-d H:i:s',
    'dateByDefault' => 'Y-m-d',
    'datePickerDefault' => 'yyyy-mm-dd',
    'themesIconsFolder' => '/assets/img/accions/',
    'themesLogosFolder' => '/assets/img/logos/',
    'themesModulesFolder' => '/assets/img/modules/',
    'documentFolder' => '/uploads/',
    //'imgFolder' => '/site/getimage/?route=/uploads/',
    'imgFolder' => '/web/img/productos/',
    'FileExtensions' => ['jpg','png','pdf'],
    'MaxFileSize' => 1024,//Tamaño 1 MB
    'timeRecursive' => '2',// segundos
    'numRecursive' => '3',
    'keywordEncription' => 'PBdoHUHYU909854874HNGFGKO',
    'tokenid' => 'HU787390kdnhyyejkKJHWFDSYWUQB72573LOSNQ2JKTDCA67253',
    'numbersecret' => '29839813211919',
    'socialNetworks' => [
        'facebook' => 'https://www.facebook.com/utimpor',
        'twitter'  => 'https://twitter.com/utimpor',
        'youtube'  => 'https://www.youtube.com/user/utimpor',
    ],
    'p_venta' => 'PAUX_03',
];